// Generated by Claude Code
import rateLimit from "express-rate-limit";

const WINDOW_MS = 15 * 60 * 1000; // 15 minutos en milisegundos

// Capa 1: Límite global — protección general contra abuso
export const globalLimiter = rateLimit({
  windowMs: WINDOW_MS,
  max: 200,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many requests, please try again later" }
});

// Capa 2: Límites por ruta — protección granular según coste de operación

export const shortenLimiter = rateLimit({
  windowMs: WINDOW_MS,
  max: 10,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many shorten requests, please try again later" }
});

export const redirectLimiter = rateLimit({
  windowMs: WINDOW_MS,
  max: 100,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many redirect requests, please try again later" }
});

export const statsLimiter = rateLimit({
  windowMs: WINDOW_MS,
  max: 50,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many stats requests, please try again later" }
});
