// Generated by Claude Code
import { Request, Response, NextFunction } from "express";
import validator from "validator";

export function validateUrl(req: Request, res: Response, next: NextFunction): void {
  const { url } = req.body;

  if (url === undefined || url === null || typeof url !== "string") {
    res.status(400).json({ error: "URL is required" });
    return;
  }

  if (url.trim() === "") {
    res.status(400).json({ error: "URL cannot be empty" });
    return;
  }

  if (url.length > 2048) {
    res.status(400).json({ error: "URL is too long (max 2048 characters)" });
    return;
  }

  if (!validator.isURL(url, { require_protocol: true })) {
    res.status(400).json({ error: "Invalid URL format. Protocol (http/https) required." });
    return;
  }

  // Block dangerous protocols (javascript:, file:, etc.)
  const protocol = url.split(":")[0].toLowerCase();
  if (!["http", "https"].includes(protocol)) {
    res.status(400).json({ error: "Only HTTP and HTTPS protocols are allowed" });
    return;
  }

  next();
}
