// Generated by Claude Code
import { Router, Request, Response } from "express";
import { getUrlByShortCode, incrementClicks } from "../services/urlService";

const router = Router();

router.get("/:shortCode", async (req: Request<{ shortCode: string }>, res: Response): Promise<void> => {
  try {
    const { shortCode } = req.params;

    const url = await getUrlByShortCode(shortCode);

    if (!url) {
      res.status(404).json({ error: "Short URL not found" });
      return;
    }

    // Incrementar contador de clicks (async, no bloqueante)
    incrementClicks(shortCode).catch((error) => {
      console.error("Error incrementing clicks:", error);
    });

    // Redirigir con status 302 (Found)
    res.redirect(302, url.originalUrl);
  } catch (error) {
    console.error("Error redirecting:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
