// Generated by Claude Code
import { Router, Request, Response } from "express";
import { shortenUrl } from "../services/urlService";
import { validateUrl } from "../middleware/validateUrl";

const router = Router();

router.post("/shorten", validateUrl, async (req: Request, res: Response): Promise<void> => {
  try {
    const { url } = req.body;
    const urlEntity = await shortenUrl(url);

    const baseUrl = process.env.BASE_URL || "http://localhost:3000";
    const shortUrl = `${baseUrl}/${urlEntity.shortCode}`;

    res.status(201).json({
      shortUrl,
      shortCode: urlEntity.shortCode,
      originalUrl: urlEntity.originalUrl
    });
  } catch (error) {
    console.error("Error shortening URL:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
