// Generated by Claude Code
import { Router, Request, Response } from "express";
import { getUrlStats } from "../services/urlService";

const router = Router();

router.get("/stats/:shortCode", async (req: Request<{ shortCode: string }>, res: Response): Promise<void> => {
  try {
    const { shortCode } = req.params;

    const url = await getUrlStats(shortCode);

    if (!url) {
      res.status(404).json({ error: "Short URL not found" });
      return;
    }

    const baseUrl = process.env.BASE_URL || "http://localhost:3000";

    res.status(200).json({
      shortCode: url.shortCode,
      originalUrl: url.originalUrl,
      shortUrl: `${baseUrl}/${url.shortCode}`,
      clicks: url.clicks,
      createdAt: url.createdAt
    });
  } catch (error) {
    console.error("Error fetching stats:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
