// Generated by Claude Code
import { AppDataSource } from "../data-source";
import { Url } from "../entities/Url";
import { generateShortCode } from "../utils/idGenerator";

const urlRepository = AppDataSource.getRepository(Url);

export async function shortenUrl(originalUrl: string): Promise<Url> {
  // Check if URL already exists
  const existing = await urlRepository.findOne({
    where: { originalUrl }
  });

  if (existing) {
    return existing;
  }

  // Generate unique code with collision retry
  let shortCode: string;
  let attempts = 0;
  const MAX_ATTEMPTS = 5;

  do {
    shortCode = generateShortCode();
    const collision = await urlRepository.findOne({
      where: { shortCode }
    });

    if (!collision) break;

    attempts++;
    if (attempts >= MAX_ATTEMPTS) {
      throw new Error("Failed to generate unique short code");
    }
  } while (true);

  // Create and save
  const url = urlRepository.create({
    shortCode,
    originalUrl,
    clicks: 0
  });

  await urlRepository.save(url);
  return url;
}

export async function getUrlByShortCode(shortCode: string): Promise<Url | null> {
  return urlRepository.findOne({ where: { shortCode } });
}

export async function incrementClicks(shortCode: string): Promise<void> {
  await urlRepository.increment({ shortCode }, "clicks", 1);
}
