// Generated by Claude Code
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn } from "typeorm";

@Entity()
export class Url {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ unique: true, length: 10 })
  shortCode!: string;

  @Column("text")
  originalUrl!: string;

  @Column({ default: 0 })
  clicks!: number;

  @CreateDateColumn()
  createdAt!: Date;
}
