// Generated by Claude Code
import { customAlphabet } from "nanoid";

// URL-safe alphabet (excluding ambiguous characters: 0, O, I, l)
const alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
const LENGTH = parseInt(process.env.SHORT_CODE_LENGTH || "7");

const nanoid = customAlphabet(alphabet, LENGTH);

export function generateShortCode(): string {
  return nanoid();
}
