// Generated by Claude Code
import request from "supertest";
import express from "express";
import rateLimit from "express-rate-limit";

// Creamos limiters con límites bajos para testing
const testGlobalLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 3,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many requests, please try again later" }
});

const testRouteLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 2,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many shorten requests, please try again later" }
});

describe("Rate Limiter Middleware", () => {
  describe("Global limiter", () => {
    let app: express.Express;

    beforeEach(() => {
      app = express();
      app.use(testGlobalLimiter);
      app.get("/test", (_req, res) => {
        res.json({ status: "ok" });
      });
    });

    it("should allow requests within the limit", async () => {
      const response = await request(app).get("/test");
      expect(response.status).toBe(200);
      expect(response.body.status).toBe("ok");
    });

    it("should return 429 when global limit is exceeded", async () => {
      // Hacer 3 requests (el límite)
      for (let i = 0; i < 3; i++) {
        await request(app).get("/test");
      }

      // El 4to debería ser rechazado
      const response = await request(app).get("/test");
      expect(response.status).toBe(429);
      expect(response.body.error).toContain("Too many requests");
    });

    it("should include RateLimit headers in response", async () => {
      const response = await request(app).get("/test");
      expect(response.headers["ratelimit-limit"]).toBeDefined();
      expect(response.headers["ratelimit-remaining"]).toBeDefined();
    });
  });

  describe("Route-specific limiter", () => {
    let app: express.Express;

    beforeEach(() => {
      app = express();
      app.get("/limited", testRouteLimiter, (_req, res) => {
        res.json({ status: "ok" });
      });
      app.get("/unlimited", (_req, res) => {
        res.json({ status: "ok" });
      });
    });

    it("should return 429 when route limit is exceeded", async () => {
      // Hacer 2 requests (el límite de ruta)
      for (let i = 0; i < 2; i++) {
        await request(app).get("/limited");
      }

      // El 3ro debería ser rechazado
      const response = await request(app).get("/limited");
      expect(response.status).toBe(429);
      expect(response.body.error).toContain("Too many shorten requests");
    });

    it("should not affect other routes without limiter", async () => {
      // Agotar el límite de /limited
      for (let i = 0; i < 3; i++) {
        await request(app).get("/limited");
      }

      // /unlimited no debería estar afectada
      const response = await request(app).get("/unlimited");
      expect(response.status).toBe(200);
    });
  });
});
