// Generated by Claude Code
import request from "supertest";
import express from "express";
import redirectRouter from "../../src/routes/redirect";
import * as urlService from "../../src/services/urlService";

jest.mock("../../src/services/urlService");

const app = express();
app.use("/", redirectRouter);

describe("GET /:shortCode", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("should redirect to original URL with 302", async () => {
    (urlService.getUrlByShortCode as jest.Mock).mockResolvedValue({
      id: 1,
      shortCode: "abc1234",
      originalUrl: "https://example.com",
      clicks: 0,
      createdAt: new Date()
    });
    (urlService.incrementClicks as jest.Mock).mockResolvedValue(undefined);

    const response = await request(app)
      .get("/abc1234")
      .expect(302);

    expect(response.headers.location).toBe("https://example.com");
    expect(urlService.incrementClicks).toHaveBeenCalledWith("abc1234");
  });

  it("should return 404 for non-existent short code", async () => {
    (urlService.getUrlByShortCode as jest.Mock).mockResolvedValue(null);

    const response = await request(app)
      .get("/notfound")
      .expect(404);

    expect(response.body.error).toContain("not found");
    expect(urlService.incrementClicks).not.toHaveBeenCalled();
  });

  it("should still redirect even if incrementClicks fails", async () => {
    (urlService.getUrlByShortCode as jest.Mock).mockResolvedValue({
      id: 1,
      shortCode: "abc1234",
      originalUrl: "https://example.com",
      clicks: 0,
      createdAt: new Date()
    });
    (urlService.incrementClicks as jest.Mock).mockRejectedValue(new Error("DB error"));

    const response = await request(app)
      .get("/abc1234")
      .expect(302);

    expect(response.headers.location).toBe("https://example.com");
  });

  it("should return 500 on unexpected service error", async () => {
    (urlService.getUrlByShortCode as jest.Mock).mockRejectedValue(new Error("Unexpected"));

    const response = await request(app)
      .get("/abc1234")
      .expect(500);

    expect(response.body.error).toContain("Internal server error");
  });
});
