// Generated by Claude Code
import request from "supertest";
import express from "express";
import shortenRouter from "../../src/routes/shorten";
import * as urlService from "../../src/services/urlService";

jest.mock("../../src/services/urlService");

const app = express();
app.use(express.json());
app.use("/api", shortenRouter);

describe("POST /api/shorten", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("should shorten valid URL", async () => {
    (urlService.shortenUrl as jest.Mock).mockResolvedValue({
      id: 1,
      shortCode: "abc1234",
      originalUrl: "https://example.com",
      clicks: 0,
      createdAt: new Date()
    });

    const response = await request(app)
      .post("/api/shorten")
      .send({ url: "https://example.com" })
      .expect(201);

    expect(response.body).toMatchObject({
      shortCode: "abc1234",
      originalUrl: "https://example.com"
    });
    expect(response.body.shortUrl).toContain("abc1234");
  });

  it("should return same shortCode for duplicate URL", async () => {
    const existing = {
      id: 1,
      shortCode: "abc1234",
      originalUrl: "https://example.com",
      clicks: 5,
      createdAt: new Date()
    };
    (urlService.shortenUrl as jest.Mock).mockResolvedValue(existing);

    const response = await request(app)
      .post("/api/shorten")
      .send({ url: "https://example.com" })
      .expect(201);

    expect(response.body.shortCode).toBe("abc1234");
  });

  it("should reject missing URL", async () => {
    const response = await request(app)
      .post("/api/shorten")
      .send({})
      .expect(400);

    expect(response.body.error).toContain("required");
  });

  it("should reject empty URL", async () => {
    const response = await request(app)
      .post("/api/shorten")
      .send({ url: "" })
      .expect(400);

    expect(response.body.error).toContain("empty");
  });

  it("should reject URL without protocol", async () => {
    const response = await request(app)
      .post("/api/shorten")
      .send({ url: "example.com" })
      .expect(400);

    expect(response.body.error).toContain("Protocol");
  });

  it("should reject invalid URL", async () => {
    const response = await request(app)
      .post("/api/shorten")
      .send({ url: "https://not a valid url" })
      .expect(400);

    expect(response.body.error).toContain("Invalid URL");
  });

  it("should reject javascript: protocol", async () => {
    const response = await request(app)
      .post("/api/shorten")
      .send({ url: "javascript:alert(1)" })
      .expect(400);

    expect(response.body.error).toBeDefined();
  });

  it("should reject ftp: protocol", async () => {
    const response = await request(app)
      .post("/api/shorten")
      .send({ url: "ftp://files.example.com/doc.txt" })
      .expect(400);

    expect(response.body.error).toContain("HTTP and HTTPS");
  });

  it("should reject URL longer than 2048 characters", async () => {
    const longUrl = "https://example.com/" + "a".repeat(2030);

    const response = await request(app)
      .post("/api/shorten")
      .send({ url: longUrl })
      .expect(400);

    expect(response.body.error).toContain("too long");
  });

  it("should handle service errors gracefully", async () => {
    (urlService.shortenUrl as jest.Mock).mockRejectedValue(new Error("DB error"));

    const response = await request(app)
      .post("/api/shorten")
      .send({ url: "https://example.com" })
      .expect(500);

    expect(response.body.error).toContain("Internal server error");
  });
});
