// Generated by Claude Code
import request from "supertest";
import express from "express";
import statsRouter from "../../src/routes/stats";
import * as urlService from "../../src/services/urlService";

jest.mock("../../src/services/urlService");

const app = express();
app.use("/api", statsRouter);

describe("GET /api/stats/:shortCode", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("should return stats for an existing short code", async () => {
    const createdAt = new Date("2026-01-15T10:00:00.000Z");
    (urlService.getUrlStats as jest.Mock).mockResolvedValue({
      id: 1,
      shortCode: "abc1234",
      originalUrl: "https://example.com",
      clicks: 5,
      createdAt
    });

    const response = await request(app)
      .get("/api/stats/abc1234")
      .expect(200);

    expect(response.body).toEqual({
      shortCode: "abc1234",
      originalUrl: "https://example.com",
      shortUrl: "http://localhost:3000/abc1234",
      clicks: 5,
      createdAt: createdAt.toISOString()
    });
    expect(urlService.getUrlStats).toHaveBeenCalledWith("abc1234");
  });

  it("should return 404 for non-existent short code", async () => {
    (urlService.getUrlStats as jest.Mock).mockResolvedValue(null);

    const response = await request(app)
      .get("/api/stats/notfound")
      .expect(404);

    expect(response.body.error).toContain("not found");
  });

  it("should return 500 on unexpected service error", async () => {
    (urlService.getUrlStats as jest.Mock).mockRejectedValue(new Error("DB error"));

    const response = await request(app)
      .get("/api/stats/abc1234")
      .expect(500);

    expect(response.body.error).toContain("Internal server error");
  });
});
