// Generated by Claude Code
import "reflect-metadata";
import express from "express";
import { AppDataSource } from "./data-source";
import shortenRouter from "./routes/shorten";

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(express.json());

// Routes
app.use("/api", shortenRouter);

// Health check
app.get("/health", (_req, res) => {
  res.json({ status: "ok" });
});

// Initialize database and start server
AppDataSource.initialize()
  .then(() => {
    console.log("✓ Database connected");

    app.listen(PORT, () => {
      console.log(`✓ Server running on http://localhost:${PORT}`);
    });
  })
  .catch((error) => {
    console.error("✗ Database connection failed:", error);
    process.exit(1);
  });

export default app;
