// Generated by Claude Code
import { generateShortCode } from "../../src/utils/idGenerator";

describe("idGenerator.generateShortCode", () => {
  it("should generate a 7-character code by default", () => {
    const code = generateShortCode();
    expect(code).toHaveLength(7);
  });

  it("should generate unique codes", () => {
    const codes = new Set<string>();
    for (let i = 0; i < 100; i++) {
      codes.add(generateShortCode());
    }
    expect(codes.size).toBe(100);
  });

  it("should only use URL-safe characters", () => {
    const code = generateShortCode();
    expect(code).toMatch(/^[A-Za-z0-9]+$/);
  });

  it("should not contain ambiguous characters (0, O, I, l)", () => {
    // Generate many codes to increase confidence
    for (let i = 0; i < 200; i++) {
      const code = generateShortCode();
      expect(code).not.toMatch(/[0OIl]/);
    }
  });
});
